import MTK

f = MTK.Window()

d = MTK.Console(minimized=True, disable_exec=True)

for i in range(100):
    d.log("YEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEETYEET", color="red")


y = MTK.Button(f, text="open console", command=d.show)
y.pack(padx=100, pady=100)

d = MTK.Scrollframe(f, show_scrollbar=True)
d.pack()

for i in range(50):
    MTK.Button(d, text="YEEE", command=lambda: MTK.Popup(f)).pack(padx=1, pady=1)

f.mainloop()